trigger:
  - develop
  - test
  - preprod
  - prod
  
variables:
  - name: SonarQubeServiceConnection
    value: 'ADO_SonarQube'
stages:

- stage: Build
  variables:
    - group: VG-BuildStageConfig

  jobs:
  - job: BuildJob
    pool:
      name: 'ADOBuildPool'
    
    steps:
    # FOR TROUBLESHOOTING ONLY.  Uncomment to skip wiping the agent build folder.  Use in conjunction with removing npm ci.
    - checkout: self
      clean: false

    # scannerMode MUST be 'cli' for npm.  Also corresponding cliProjectKey, Name 
    - task: SonarQubePrepare@8
      displayName: 'Prepare SonarQube Analysis'
      inputs:
        SonarQube: '$(SonarQubeServiceConnection)'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: '$(SonarQubeProjectKey)'
        cliProjectName: '$(SonarQubeProjectName)'
        cliSources: '.'
        extraProperties: |
          sonar.exclusions=**/node_modules/**
        # sonar.exclusions=**/dist/**
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        # The two lines below are what will cause the build to fail if it doesn't meet the quality gate. This might not be best practice according to SonarQube
        #  sonar.qualitygate.wait=true
        #  sonar.qualitygate.timeout=300

    # Creates .npmrc file so that we can pull packages from our repo
    - powershell: |
        Write-Host "Creating .npmrc with auth token..."

        $registry = "https://farmers-merchants-bank.repo.sonatype.app/repository/npm-proxy/"

        @"
        registry=$registry
        //farmers-merchants-bank.repo.sonatype.app/repository/npm-proxy/:_auth=$(NexusAuthToken)
        "@ | Out-File -FilePath .npmrc -Encoding ascii
      displayName: "Create .npmrc"

    # Run if npm ci found in commit comment
    - script:  |
        npm ci --prefer-offline --loglevel info
      displayName: "Install node modules"
      condition: contains(variables['Build.SourceVersionMessage'], 'npm ci')

    - script: |
        npm run build
      displayName: "Build Node.JS Project"

    - task: SonarQubeAnalyze@8
      displayName: 'Run SonarQube Analysis'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')

    - task: SonarQubePublish@8
      displayName: 'Publish SonarQube results'
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      inputs:
        pollingTimeoutSec: '300'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*
          !**/node_modules/**
          !**/PipelineTemplates/**
          !**/azure-pipelines.yml
          !.git/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy files excluding certain directories'

    - task: PublishBuildArtifacts@1
      displayName: "Publish CIQ Artifact"
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(Build.Repository.Name)'
        publishLocation: 'Container'

    - powershell: |
        Remove-Item .\.npmrc
      displayName: "Delete .npmrc"
    
    # Grabbing commit message to send downstream to other stages for 'npm ci' check
    - script: |
            echo ##vso[task.setvariable variable=commitMessage;isOutput=true]$(Build.SourceVersionMessage)
      name: buildVar
      displayName: "Capturing Commit Comment"

# Dev Deploy stage
- stage: Deploy_Dev
  condition:  eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  dependsOn: Build
  variables:
    - group: VG-Dev
    - name: SAMLRoleEnv         # scopes ClientIQ AD-group role mapping to this env
      value: DEV
    - name: commitMessage
      value: $[stageDependencies.Build.BuildJob.outputs['buildVar.commitMessage'] ]
  jobs:
  - deployment: DevDeployment
    environment: 'Dev'
    pool:
      name: 'ADODeployPool_DevTest'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:

          - template: PipelineTemplates/start-script.yml
          - template: PipelineTemplates/deploy-nodejs.yml

# Test Deploy stage
- stage: Deploy_Test
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/test')
  dependsOn: Build
  variables:
    - group: VG-Test
    - name: SAMLRoleEnv         # scopes ClientIQ AD-group role mapping to this env
      value: TST
    - name: commitMessage
      value: $[stageDependencies.Build.BuildJob.outputs['buildVar.commitMessage'] ]

  jobs:
  - deployment: TestDeployment
    environment: 'Test'
    pool:
      name: 'ADODeployPool_DevTest'

    strategy:
      runOnce:
        deploy:
          steps:

          - template: PipelineTemplates/start-script.yml
          - template: PipelineTemplates/deploy-nodejs.yml
          

# DAST Scan to run after Test deployed 
- stage: DAST_Scan
  dependsOn: Deploy_Test
  condition: succeeded()
  
  variables:
    - group: VG-DASTConfig

  jobs:
  - job: 'Scan'
    displayName: 'ZAP DAST Scan'
    pool:
      name: 'ADODeployPool_DevTest'

    steps:
      - checkout: none
      
      - template: PipelineTemplates/dast-scan.yml


# Preprod Deploy stage
- stage: Deploy_Preprod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/preprod')
  dependsOn: Build
  variables:
    - group: VG-Preprod
    - name: SAMLRoleEnv         # scopes ClientIQ AD-group role mapping to this env
      value: STG
    - name: commitMessage
      value: $[stageDependencies.Build.BuildJob.outputs['buildVar.commitMessage'] ]

  jobs:
  - deployment: PreprodDeployment
    environment: 'PreProd'
    pool:
      name: 'ADODeployPool'

    strategy:
      runOnce:
        deploy:
          steps:

          - template: PipelineTemplates/start-script.yml
          - template: PipelineTemplates/deploy-nodejs.yml


# Prod Deploy stage Server 1
- stage: Deploy_Prod
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/prod')
  dependsOn: Build
  variables:
    - group: VG-Prod
    - name: SAMLRoleEnv         # scopes ClientIQ AD-group role mapping to this env
      value: PRD
    - name: commitMessage
      value: $[stageDependencies.Build.BuildJob.outputs['buildVar.commitMessage'] ]

  jobs:
  - deployment: ProdDeployment
    environment: 'Prod'
    pool:
      name: 'ADODeployPool'

    strategy:
      runOnce:
        deploy:
          steps:

          - template: PipelineTemplates/start-script.yml
          - template: PipelineTemplates/deploy-nodejs.yml


# Prod Deploy stage Server 2
- stage: Deploy_Prod2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/prod')
  dependsOn: Build
  variables:
    - group: VG-Prod2
    - name: SAMLRoleEnv         # scopes ClientIQ AD-group role mapping to this env
      value: PRD
    - name: commitMessage
      value: $[stageDependencies.Build.BuildJob.outputs['buildVar.commitMessage'] ]

  jobs:
  - deployment: ProdDeployment
    environment: 'Prod'
    pool:
      name: 'ADODeployPool'

    strategy:
      runOnce:
        deploy:
          steps:

          - template: PipelineTemplates/start-script.yml
          - template: PipelineTemplates/deploy-nodejs.yml